@url = http://localhost:3000/card
@cardId = 1
@columnId = 1
@managerId = 1


GET {{url}}/{{columnId}}

###
POST {{url}}
Content-Type: application/json

{
    "columnId": {{columnId}},
    "title": "할일",
    "backgroundColor": "blue",
    "description": "card api",
    "position": 1
}

###
PUT {{url}}/{{cardId}}
Content-Type: application/json

{
    "title": "시험",
    "backgroundColor": "yellow",
    "description": "ㅇㄹ냐ㅗ",
    "managerId": {{managerId}}
}

###
DELETE {{url}}/{{cardId}}


