@url = http://localhost:3000/card
@cardId = 2
@columnId = 1
@managerId = 1
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNzA0ODg3MzAxLCJleHAiOjE3MDQ4OTA5MDF9.JPVRDezMH42S5D4MYvduvCwuvQRrRn1wtUV57wZmFS0


GET {{url}}/{{columnId}}
Authorization: {{token}}
###
POST {{url}}
Content-Type: application/json
Authorization: {{token}}

{
    "columnId": {{columnId}},
    "title": "할일",
    "backgroundColor": "blue",
    "description": "card api",
    "position": 1
}

###
PUT {{url}}/{{cardId}}
Content-Type: application/json
Authorization: {{token}}

{
    "title": "시험",
    "backgroundColor": "yellow",
    "description": "ㅇㄹ냐ㅗ",
    "managerId": {{managerId}}
}

###
DELETE {{url}}/5
Authorization: {{token}}

###카드 데드라인 지정 / Thunder Client로 실행 필수(Rest 오류남)
PUT {{url}}/3/deadline
Authorization: {{token}}

{
    "deadline": "{{$datetime iso8601}}"
}

###카드 위치변경
PUT {{url}}/4/position
Authorization: {{token}}

{
    "prevCardId": null,
    "nextCardId": 2
}