@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNzA0OTA0ODY3LCJleHAiOjE3MDQ5MDg0Njd9.DoJlK7Z4F-GlCHSuRhyHOga5M2_nxJ-NutiKaC2_9I0
@boardId = 5
@columnId = 1
###
// 컬럼 생성
POST http://localhost:3000/board/{{boardId}}/column
Content-Type: application/json
Authorization: {{token}}

{
  "title": "첫 타이틀"
}

###
// 컬럼 순서 이동
PUT http://localhost:3000/board/{{boardId}}/column/{{columnId}}/position
Content-Type: application/json
Authorization: {{token}}

{
  "preColumnId": 9,
  "nextColumnId": 11
}

###
// 컬럼 이름 수정
PUT http://localhost:3000/board/boardId/column/columnId
Content-Type: application/json
Authorization: {{token}}

{
    "title": "타이틀 수정입니다."
}

###
// 컬럼 삭제
DELETE http://localhost:3000/board/boardId/column/columnId
Content-Type: application/json
Authorization: {{token}}


###
// 컬럼 전체 조회
GET http://localhost:3000/board/boardId/column/
Content-Type: application/json
Authorization: {{token}}
